package by.vadim_churun.individual.progen

import by.vadim_churun.individual.progen.engine.create.TemplateDriverLoader
import by.vadim_churun.individual.progen.model.engine.MutableArguments
import java.io.FileOutputStream
import java.io.PrintWriter


fun main() {
    val driver = TemplateDriverLoader.get("reactPackage")

    val args = MutableArguments()
    args.add("projectName", "Autogenerated")
    args.add("reactVersion", "1.2.3")

    FileOutputStream("autogenerated.json").use { ostream ->
        PrintWriter(ostream).use { writer ->
            driver.generate(writer, args)
        }
    }
}